# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-07-12T05:24:55+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, conint


class Pet(BaseModel):
    name: Optional[str] = None
    age: Optional[int] = None


class Dog(Pet):
    color: Optional[str] = None


class Person(BaseModel):
    first_name: str = Field(..., description="The person's first name.")
    last_name: str = Field(..., description="The person's last name.")
    age: Optional[conint(ge=0, le=200)] = Field(None, description='Age in years.')
    pets: Optional[List[Pet]] = Field(None, max_length=5)
    comment: None = None
